### ISSUE TITLE
Codesandbox not working

### ISSUE THREAD

**Issue by anilanar** [nrdlab/pattern-matching-ts#1]
https://codesandbox.io/s/festive-lovelace-mfrx4

Is the package misconfigured or?

**Comment by nrdlab** [comment]
Hi @anilanar,
I just released 
- a new version 📦  that adds index exporting!
- updated documentation with the correct import example.

Thanks for taking the time to open this issue...

**Comment by anilanar** [comment]
@nrdlab Do you have a functional codesandbox? I still couldn't make it work. The types work now, but importing/bundling part still seems to have a problem.
